value = input('Type one value: ')
print('The primitive value is {}'.format(type(value)))
print('Just have spaces?', value.isspace())
print('Is a number?', value.isnumeric())
print('Is alphabet?', value.isalpha())
print('Is alphanumeric?', value.isalnum())
print('Is it in capital letter?', value.isupper())
print('Is it in lower case?', value.islower())
print('Is it capitalized?', value.istitle())
